### ISSUE TITLE
如何加载特定step保存的模型？

### ISSUE THREAD

**Issue by Taoooo9** [Macielyoung/Bloom-Lora#4]
请问是不是模型训练完才会生成adapter_config.json和adapter_model.bin文件？目前，模型还在训练，只得到了如下的文件：
![image](https://user-images.githubusercontent.com/41136544/232447265-2fd23e12-be75-4cf3-b051-fb517f279749.png)
请问这些文件可以加载吗？和adapter_model.bin有什么区别？

**Comment by Macielyoung** [comment]
pytorch_model.bin就是adapter_model.bin，可以改一下名字。config json没有保存下来，可以自己编辑一下，参考一下llama微调出的模型配置文件(https://huggingface.co/chainyo/alpaca-lora-7b/blob/main/adapter_config.json)。

**Comment by Taoooo9** [comment]
谢谢

**Comment by Taoooo9** [comment]
> pytorch_model.bin就是adapter_model.bin，可以改一下名字。config json没有保存下来，可以自己编辑一下，参考一下llama微调出的模型配置文件([https://huggingface.co/chainyo/alpaca-lora-7b/blob/main/adapter_config.json)。](https://huggingface.co/chainyo/alpaca-lora-7b/blob/main/adapter_config.json)%E3%80%82)

谢谢
